# Generated by Django 3.2.10 on 2025-01-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Customer Feedback', 'verbose_name_plural': 'Customer Feedback'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(max_length=50, verbose_name='Customer name'),
        ),
    ]
